---
- name: Converge
  hosts: all
  roles:
    - role: lean_delivery.java
      java_distribution: openjdk
      transport: chocolatey
      java_major_version: 12
      java_minor_version: 0.1
    - role: ansible-role-zookeeper
