---
- name: Converge
  hosts: all
  roles:
    - role: lean_delivery.java
      transport: repositories
      java_major_version: 8
    - role: ansible-role-zookeeper
      zk_force_myid: false
      zk_force_config: false
      zk_version: 3.5.5
