---
- name: Zookeeper Installation
  include_tasks: '{{ zk_install_type }}.yml'

- name: Enable zookeeper service
  service:
    name: '{{ zk_service_name }}'
    enabled: true
  register: dbg
  become: true
  when:
    - zk_service_autostart

- name: Check Zookeeper service status
  service:
    name: 'zookeeper'
  check_mode: true
  register: zookeeper_status

- name: Debug zookeeper_status
  debug:
    var: zookeeper_status

- name: Start service
  service:
    name: '{{ zk_service_name }}'
    state: started
  become: true
  when:
    - zk_service_start
