---

- name: Install zookeeper from chocolatey
  win_chocolatey:
    name: apache-zookeeper
    package_params: "unzipLocation=C:/zookeeper/"
  register: choco_install
  retries: 15
  delay: 5
  until: choco_install is succeeded

- name: Create log directory
  win_file:
      path: '{{ zk_log_dir }}'
      state: directory

- name: Create data directory
  win_file:
      path: '{{ zk_data_dir }}'
      state: directory
