---
- name: 'Download artifact from {{ zk_url }}'
  win_get_url:
    url: '{{ zk_url }}'
    dest: '{{ zk_tarball_dir }}\zookeeper-{{ zk_version }}.tar.gz'
    force: true

- name: 'Get sha512 checksum of file'
  win_stat:
    path: '{{ zk_tarball_dir }}\zookeeper-{{ zk_version }}.tar.gz'
    get_checksum: true
    checksum_algorithm: 'sha512'
  register: artifact
