---
- name: Debug
  debug:
    msg: 'Windows installation'

- name: Check choco
  win_chocolatey:
    name: chocolatey
    state: present

- name: "Install nssm"
  win_chocolatey:
    name: nssm
    state: present

- name: Zookeeper Installation
  include_tasks: '{{ zk_install_type }}.yml'

- name: Set an environment variable zookeperhome
  win_environment:
    state: present
    name: ZOOKEEPER_HOME
    value: '{{ zk_default_dir }}'
    level: machine

- name: Set path
  win_path:
    elements: '%ZOOKEEPER_HOME%\bin'
    state: present
    level: machine

- name: Create log directory
  win_file:
      path: '{{ zk_default_log_dir }}'
      state: directory

- name: Configure zookeeper zoo.cfg config
  win_template:
    src: 'Win32NT/zoo.cfg.j2'
    dest: '{{ zk_package_config_dir }}/zoo.cfg'

- name: Configure zookeeper log4j.properties config
  win_template:
    src: 'log4j.properties.j2'
    dest: '{{ zk_package_config_dir }}/log4j.properties'

- name: "Create a service via nssm"
  win_nssm:
    name: '{{ zk_service_name }}'
    application: '{{ zk_dir }}/bin/zkserver.cmd'
    state: present

- name: "Start the service"
  win_service:
    name: '{{ zk_service_name }}'
    state: started
