---
- name: Debug
  debug:
    msg: 'Windows installation'

- name: Zookeeper Installation
  include_tasks: '{{ zk_install_type }}.yml'

- name: Set an environment variable zookeperhome
  win_environment:
    state: present
    name: ZOOKEEPER_HOME
    value: '{{ zk_default_dir }}'
    level: machine

- name: Set path
  win_path:
    elements: '%ZOOKEEPER_HOME%\bin'
    state: present
    level: machine

- name: Create log directory
  win_file:
      path: '{{ zk_default_log_dir }}'
      state: directory

- name: Configure zookeeper zoo.cfg config
  win_template:
    src: 'Win32NT/zoo.cfg.j2'
    dest: '{{ zk_package_config_dir }}/zoo.cfg'

- name: Configure zookeeper log4j.properties config
  win_template:
    src: 'log4j.properties.j2'
    dest: '{{ zk_package_config_dir }}/log4j.properties'

- name: Create a new service with extra details
  win_service:
    name: zkserver_service7
    path: 'C:\tools\zookeeper-3.4.9\bin\zkServer.cmd'
    display_name: Zookeperserver7
    username: NetworkService
    state: started
    start_mode: auto

#- name: Configure zookeeper zoo.cfg and log4j config
#  win_template:
#    src: '{{ config }}.j2'
#    dest: '{{ zk_package_config_dir }}/{{ config }}'
#  loop: '{{ zk_config_file_list }}'
#  loop_control:
#    loop_var: config
