---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: delegated
lint:
  name: yamllint
  options:
    config-file: molecule/yamllint.yml
platforms:
  - name: test-aws-centos7-zookeeper
    shape: small
    image: CentOS7_64-bit
    region: AWS-EUCENTRAL
    wait_timeout: 1800
    groups:
      - zookeeper
      - zookeeper_centos
  - name: test-aws-ubuntu1804-zookeeper
    shape: small
    image: Ubuntu18.04_64-bit
    region: AWS-EUCENTRAL
    wait_timeout: 1800
    groups:
      - zookeeper
      - zookeeper_ubuntu
provisioner:
  name: ansible
  log: True
  playbooks:
    create: ../resources/provisioning/create.yml
    prepare: ../resources/provisioning/prepare.yml
    destroy: ../resources/provisioning/destroy.yml
  config_options:
    ssh_connection:
      control_path: "/var/ans/%%h"
  lint:
    name: ansible-lint
  env:
    ANSIBLE_LIBRARY: ${ANSIBLE_LIBRARY}
scenario:
  name: cloud-aws-delegated
verifier:
  name: testinfra
  options:
    verbose: true
  directory: ../resources/tests/
  lint:
    name: flake8
